version: '3'

services:
  site:
    image: potdig/rttr-gen2
    build:
      context: .
    volumes:
      - ./src:/work/src
      - ./public:/work/public
      - ./vite.config.ts:/work/vite.config.ts
      - ./graphics:/work/graphics
    ports:
      - 5173:5173
    restart: always
  nodecg:
    image: potdig/rttr-gen2-nodecg
    build:
      dockerfile: Dockerfile.nodecg
    volumes:
      - ./dist/graphics:/app/nodecg/bundles/${LAYOUTS_NAME}/graphics
      - ./dist/web-assets:/app/nodecg/bundles/${LAYOUTS_NAME}/web-assets
    ports:
      - 9090:9090