import type { Commentator } from '~/types/commentator'
import type { Group } from '~/types/group'
import type { Runner } from '~/types/runner'

const runners: Array<Runner> = [
  {
    group: 'A',
    order: 1,
    name: 'Runner A1',
    gameTitle: 'Game A1',
    category: 'Any%',
    console: 'AAA',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_a1',
    streamText: 'Twitch: runner_a1',
    icon: 'a.png',
  },
  {
    group: 'B',
    order: 1,
    name: 'Runner B1',
    gameTitle: 'Game B1',
    category: 'Bny%',
    console: 'BBB',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_b1',
    streamText: 'Twitch: runner_b1',
    icon: 'b.png',
  },
  {
    group: 'C',
    order: 1,
    name: 'Runner C1',
    gameTitle: 'Game C1',
    category: 'Cny%',
    console: 'CCC',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_c1',
    streamText: 'Twitch: runner_c1',
    icon: 'c.png',
  },
  {
    group: 'D',
    order: 1,
    name: 'Runner D1',
    gameTitle: 'Game D1',
    category: 'Dny%',
    console: 'DDD',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_d1',
    streamText: 'Twitch: runner_d1',
    icon: 'd.png',
  },
  {
    group: 'A',
    order: 2,
    name: 'Runner A2',
    gameTitle: 'Game A2',
    category: 'Any%',
    console: 'AAA',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_a2',
    streamText: 'Twitch: runner_a2',
    icon: 'a.png',
  },
  {
    group: 'B',
    order: 2,
    name: 'Runner B2',
    gameTitle: 'Game B2',
    category: 'Bny%',
    console: 'BBB',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_b2',
    streamText: 'Twitch: runner_b2',
    icon: 'b.png',
  },
  {
    group: 'C',
    order: 2,
    name: 'Runner C2',
    gameTitle: 'Game C2',
    category: 'Cny%',
    console: 'CCC',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_c2',
    streamText: 'Twitch: runner_c2',
    icon: 'c.png',
  },
  {
    group: 'D',
    order: 2,
    name: 'Runner D2',
    gameTitle: 'Game D2',
    category: 'Dny%',
    console: 'DDD',
    targetTime: '1:00:00',
    personalBest: '1:10:00',
    limitTime: '3:00:00',
    twitter: '@runner_d2',
    streamText: 'Twitch: runner_d2',
    icon: 'd.png',
  },
]

const commentators: Array<Commentator> = [
  {
    name: 'Comment A',
    icon: 'comm_a.png',
    linkIds: [['A', 2]],
  },
  {
    name: 'Comment B',
    icon: 'comm_a.png',
    linkIds: [['B', 1]],
  },
  {
    name: 'MC 1',
    icon: 'mc_1.png',
    linkIds: ['MC'],
  },
  {
    name: 'MC 2',
    icon: 'mc_2.png',
    linkIds: ['MC'],
  },
  {
    name: 'えむしー3',
    icon: 'mc_3.png',
    linkIds: ['MC'],
  },
]
const currentRunners: Array<[Group, number]> = [
  ['A', 1],
  ['B', 1],
  ['C', 1],
  ['D', 1],
]

const isSettingUp: Array<[Group, boolean]> = [
  ['A', false],
  ['B', false],
  ['C', false],
  ['D', false],
]

export { runners, commentators, currentRunners, isSettingUp }
